# Generated by Django 4.1 on 2022-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vitals_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('temperature_flag', models.IntegerField()),
                ('systolic_bp', models.FloatField()),
                ('systolic_bp_flag', models.IntegerField()),
                ('diastolic_bp', models.FloatField()),
                ('diastolic_bp_flag', models.IntegerField()),
                ('pulse_rate', models.FloatField()),
                ('pulse_rate_flag', models.IntegerField()),
                ('oxygen_saturation', models.FloatField()),
                ('oxygen_saturation_flag', models.IntegerField()),
            ],
        ),
    ]
