# Generated by Django 4.1 on 2022-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHABOTapp', '0002_vitals_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals_data',
            name='user',
        ),
        migrations.AddField(
            model_name='vitals_data',
            name='exercise_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vitals_data',
            name='exercise_prediction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vitals_data',
            name='exercise_stream',
            field=models.ImageField(default='images/img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vitals_data',
            name='exercise_stream_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='diastolic_bp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='diastolic_bp_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='oxygen_saturation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='oxygen_saturation_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='pulse_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='pulse_rate_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='systolic_bp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='systolic_bp_flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vitals_data',
            name='temperature_flag',
            field=models.IntegerField(default=2),
        ),
    ]
