# Generated by Django 4.1 on 2022-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHABOTapp', '0003_remove_vitals_data_user_vitals_data_exercise_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals_data',
            name='exercise_stream',
            field=models.BinaryField(),
        ),
    ]
