# Generated by Django 4.1 on 2022-08-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IHABOTapp', '0004_alter_vitals_data_exercise_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitals_data',
            old_name='diastolic_bp_flag',
            new_name='bp_flag',
        ),
        migrations.RemoveField(
            model_name='vitals_data',
            name='exercise_stream',
        ),
        migrations.RemoveField(
            model_name='vitals_data',
            name='exercise_stream_flag',
        ),
        migrations.RemoveField(
            model_name='vitals_data',
            name='pulse_rate_flag',
        ),
        migrations.RemoveField(
            model_name='vitals_data',
            name='systolic_bp_flag',
        ),
    ]
